stages:
  - build
  - test

buildEventFiesta:
  stage: build
  image: maven:latest
  script:
    - echo "Building Event Fiesta"
    - mvn clean package -Dmaven.test.skip=true
  artifacts:
    paths:
      - target/Output/Artifacts
  tags:
    - ugrad

testEventFiesta:
  stage: test
  image: maven:latest
  script:
    - echo "Testing Event Fiesta"
    - mvn verify
  artifacts:
    paths:
      - target/Output/Artifacts
  tags:
    - ugrad