stages:
  - build
  - test
  - deploy

buildEventFiesta:
  stage: build
  image: maven:latest
  script:
    - echo "Building Event Fiesta"
    - mvn clean package -Dmaven.test.skip=true
  artifacts:
    paths:
      - target
  tags:
    - ugrad

testEventFiesta:
  stage: test
  image: maven:latest
  script:
    - echo "Testing Event Fiesta"
    - mvn verify
  artifacts:
    paths:
      - target
  tags:
    - ugrad

deployEventFiesta:
  stage: deploy
  image: maven:latest
  script:
    - echo "Deploy Event Fiesta to Heroku"
    - gem install dp
    - dpl --provider=heroku --app=$APP_NAME --apikey=$APP_KEY
  artifacts:
    paths:
      - target
  tags:
    - ugrad
  only:
    - develop